name: Analyze Code with SonarCloud, Pull Docker Image, and Build Application

on:
  push:
    branches:
      - master

jobs:
  analyze_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Analyze in Docker
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
        run: |
          docker build -f Dockerfile.sonar -t my-analysis-image .
          docker run --rm \
            -v ${{ github.workspace }}:/usr/src/app \
            -e SONAR_TOKEN=$SONAR_TOKEN \
            -e SONAR_PROJECT_KEY=$SONAR_PROJECT_KEY \
            -e SONAR_ORGANIZATION_KEY=$SONAR_ORGANIZATION_KEY \
            my-analysis-image
            -X
